name: Check App

on: 
  push:
    branches:
      - main

jobs:
  check-app:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: 'executors-org'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Build
        run: yarn build